server:
  port: 9090

#=================================微信相关====================================
#公众号
wxpay:
  appid: wx5beac15ca207cdd40c
  appsecret: 5548012f33417fdsdsdd6f96b382fe548215e9

#开放平台
wxopen:
  appid: wxe9ef2df5e786b62a
  appsecret: c973a39ce5d2638e95f251a893cdfac4
  redirect_url: http://xdclasstest2.ngrok.xiaomiqiu.cn/pub/api/v1/wechat/user/callback1

#=================================数据库相关====================================
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///xd_video?useUnicode=true&chararcterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

#=================================Mybatis相关====================================
mybatis:
  configuration:
    # 下划线转驼峰配置
    map-underscore-to-camel-case: true
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl