server:
  port: 9090

#=================================微信相关====================================
#公众号
wxpay:
  appid: wx5k69f62m3jdjwx9e
  appsecret: h38v6b05ulmi08723l8jug05hk5ct0dc
  #支付配置
  #微信商户平台
  mch_id: 6076622174
  key: Iz0WOx1E6O17p1j03Q423a6gLQTL8w9g
  notify_url: http://xdclasstest2.ngrok.xiaomiqiu.cn/api/v1/wechat/order/callback


#开放平台
wxopen:
  appid: wxe9ef2df5e786b62a
  appsecret: c973a39ce5d2638e95f251a893cdfac4
  redirect_url: http://xdclasstest2.ngrok.xiaomiqiu.cn/api/v1/wechat/user/callback

#=================================数据库相关====================================
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///xc_video?useUnicode=true&chararcterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/static,classpath:/templates

#=================================Mybatis相关====================================
mybatis:
  configuration:
    # 下划线转驼峰配置
    map-underscore-to-camel-case: true
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl